name: CI

on: [push]

jobs:
  lint:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: yarn install
      run:  sudo apt-get update && sudo apt-get install yarn
    
    steps:
    - name: package install
      run:  yarn
    - name: lint
      run:  yarn lint
