name: CI

on: [push]

jobs:
  check:

    runs-on: ubuntu-latest
    container:
      image: yarnpkg/node-yarn
    steps:
    - uses: actions/checkout@v1
    - name: package install
      run:  yarn
    - name: lint
      run:  yarn lint
    - name: test
      run:  yarn test:headless

